name: CI
on:
  push:
    branches:
      - "**" # matches every branch
      - "!main" # excludes master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 7
      - uses: actions/setup-node@v4
        with:
          node-version: 16.x
          cache: "pnpm"
      - run: pnpm install --no-frozen-lockfile
      - run: pnpm run ci
      - run: pnpm run docs
