name: Publish
on:
  push:
    branches:
      - "main"

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 7
      - uses: actions/setup-node@v4
        with:
          node-version: 16.x
          cache: "pnpm"
      - run: pnpm install --no-frozen-lockfile
      - run: pnpm run ci
      - run: pnpm run docs

  publish:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 7
      - uses: actions/setup-node@v4
        with:
          node-version: 16.x
          cache: "pnpm"

      - run: pnpm install --no-frozen-lockfile
      - name: Create Release Pull Request or Publish
        id: changesets
        uses: changesets/action@v1
        with:
          publish: pnpm run publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
